# Generated by Django 3.1.4 on 2023-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_load', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avg_load', models.DecimalField(decimal_places=2, max_digits=4)),
                ('measure_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-measure_time'],
            },
        ),
    ]
