# Generated by Django 3.1.4 on 2023-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='graph',
            field=models.ImageField(blank=True, upload_to='graphs/%Y/%m/%d/%H/%M/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='measure_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
