# Generated by Django 3.1.4 on 2023-02-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpu', '0004_auto_20230220_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='graph',
        ),
    ]
